### PR TITLE
feature/eco-3340 allow new version of spryker/oms and spryker/sales

### PR DESCRIPTION
**Pull request by pyvovarov-s**
- Developer(s): @pyvovarov-s

- Ticket: https://spryker.atlassian.net/browse/ECO-3340

- Academy PR: ACADEMY_URL_HERE

- Release Group: URL_HERE

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   Computop              | patch                 |                       |

#### Release Notes

{skip}

-----------------------------------------

##### Change log

Bugfixes

Adjusted composer.json to allow for new spryker/oms major "^11.0.0".
Adjusted composer.json to allow for new spryker/sales major "^11.0.0".

### CODE REVIEW

**Comment by dereuromark** [comment]
Same issue: Invalid changelogs, you are not increasing dependency, you are "allowing a new major"

**Comment by pyvovarov-s** [comment]
> Same issue: Invalid changelogs, you are not increasing dependency, you are "allowing a new major"

But we don't have "Alow" option in RFC 
https://spryker.atlassian.net/wiki/spaces/CORE/pages/523730976/Release+Notes+and+Changelogs

**Comment by dereuromark** [comment]
You need to apply reasonable context. Those are just examples!

**Comment by pyvovarov-s** [comment]
> You need to apply reasonable context. Those are just examples!

Ahhh thx now it's clear, fixed

**Comment by dereuromark** [comment]
I clarified https://spryker.atlassian.net/wiki/spaces/CORE/pages/523730976/Release+Notes+and+Changelogs

**Pull request merged**
